name: Java CI

on:
  pull_request:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.7.0
      - uses: aahmed-se/setup-maven@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Build with Maven
        env:
          # ruleid: allowed-unsecure-commands
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: mvn --batch-mode --update-snapshots package
